### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [Frankenmint/PKGenerator_Checker#1]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-q2jLKw/hashlib/

**Comment by Frankenmint** [comment]
what happens when you try to do it with sudo?  I would have said try it w/ sudo but stack exchange says try installing setuptools first:

https://stackoverflow.com/a/36025294

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

**Comment by ghost** [comment]
Okay, so, this is the last error after trying to install on Windows and not Ubuntu VPS.

   File "hashlib.py", line 115, in <module>
        f()
    TypeError: 'frozenset' object is not callable

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\pb\appdata\local\temp\pip-install-owbfvy\hashlib\

**Comment by ghost** [comment]
Okay, lol, I fixed that. This is the last error. 

0
5KCXky1673ygKF2EssShJmt73HZMPbxbTK9KHFjf2uWaTvD6npZ
1LrJg7JGM3LVSX1XWpBr6Gm3tk529N653P
Aaaannnnd we got Timed Out
b6346e7269f2b73fbb45099f51fc51bee5ce58d4ee50d20e9175b0fe26528b68
1LrJg7JGM3LVSX1XWpBr6Gm3tk529N653P
Traceback (most recent call last):
  File "PkMaker.py", line 87, in <module>
    sleep(3)
NameError: name 'sleep' is not defined

**Comment by Frankenmint** [comment]
hmm, should be a line somewhere that said from time import sleep...otherwise it needs to be time.sleep(3) in PkMaker.py on line 87.  I'll take  look, hold on... okay I saw that it should be time.sleep and changed my code accordingly.. its literally a tiny change so I don't know if you really think its worth git pull but you can do that or jut edit the PkMaker file so that it says `time.sleep(3)` instead of sleep(3).

**Comment by ghost** [comment]
It was fixed, thanks friend. What is the probability of finding an address with a balance?

**Comment by Frankenmint** [comment]
100% with enough time.  Although the sun may be burned out long before that time approaches and mankind will long since have moved on and we'll likely be using some new iteration of tech that is no longer called bitcoin ;)
