### ISSUE TITLE
Installing Problems

### ISSUE THREAD

**Issue by 255ms** [Frankenmint/PKGenerator_Checker#13]
Hello,
I have installation problems and, to be honest, I don't really know python, so I ask if you can make a short video of how to install "pip install ecdsa hashlib base58 requests cfscrape" and then install or start the code (Navigate to the directory: cd PKGenerator_Checker and Run it python PkMaker.py). 
Thank you in advance and would like to thank you for the files and your help!

**Comment by Frankenmint** [comment]
alright what you'll need to do is to open a terminal or command line if using windows.  that command `pip install ecdsa hashlib base58 requests cfscrape` is what you'll type in, it will globally install those modules which my script will then use. here's a quick video if you have windows and you're trying to install pip: https://www.youtube.com/watch?v=dj5oOPaeIqI

**Comment by 255ms** [comment]
Ok thanks, but well I need your help again because,
1. I don't know how to Navigate the directory to cd PKGenerator_Checker 
2. Run python PkMaker.py
I know that are completely beginner questions but I really don't know how to do it and I also watched a lot of Youtube tutorials but they couldn't help me.
