### ISSUE TITLE
own hex key range

### ISSUE THREAD

**Issue by olivercito3** [Frankenmint/PKGenerator_Checker#15]
Hi want to ask if it would be possible to make own hex range in whitch will be keys created and than matched on blockchain

**Comment by jyzip** [comment]
There would be no reason to do that. Other than the puzzle sequence, keys are full generally length. This does not assist in the search.

**Comment by Frankenmint** [comment]
Not really, its a range between 0 and 2^256-1 in hex and its generated at random.  insofar as I'm aware, that space of digits is still too vast to give any sort of meaningful ranges
