### ISSUE TITLE
Remove references to actual websites

### ISSUE THREAD

**Issue by jmunson** [Frankenmint/PKGenerator_Checker#5]
Since this project's readme claims

>  This is for entertainment only and is designed to demonstrate how IMPOSSIBLE it is to realistically get a collision and take control of someone else's coin

then why have working defaults that connect to live sites? You should make the script kiddies jump through at least one hoop before DoSing a public service.

Even better would be to suggest/document how they could run their own copy of bitcoind to verify against, for whoever actually wants to demonstrate how impossible this is. Theres no need for an external service to be involved in this process.

**Comment by Frankenmint** [comment]
Hmm, I think you’re right… I’d just do an import script of all the keys on a synced node… problem is I don’t have the hard drive capacity to run a full bitcoin node right now :(  Hopefully that changes soon :)
