### ISSUE TITLE
Dump of existing public addresses?

### ISSUE THREAD

**Issue by fogoat** [Frankenmint/PKGenerator_Checker#6]
Would it be faster to have a local list of existing public addresses that the script checks again? It would avoid having to query the API?

**Comment by Frankenmint** [comment]
in theory this could work, yes, but you'd be better off creating a script that can take the raw csv and [create an import address call on your full node](https://bitcoin.stackexchange.com/a/48763/5486) - I'd imagine that this would still end up with a situation of a ton of unused addresses in a wallet that you control.
